### ISSUE TITLE
Moving to SystemRDL namespace

### ISSUE THREAD

**Issue by MarekPikula** [SystemRDL/PeakRDL-Markdown#2]
Thank you, @amykyta3, for allowing me to move the project to the SystemRDL namespace. There are a few additional things to do to make the project fully belong here:

- [x] Add collaborators to PyPI. @amykyta3 @drom Could you provide me with your PyPI usernames so that I can add you to the project?
- [x] Add collaborators to RTD. Same as obove, but for ReadTheDocs.
- [x] Move to official plugins in [.github repo](https://github.com/SystemRDL/.github) (SystemRDL/.github#1)
- [x] Replace all references to MarekPikula namespace to SystemRDL (#3).
- [x] Let me know if you have access to the Coveralls of this repo. I seem to have access to other SystemRDL repositories, so I presume it should be the same for you.
- [x] Python 3.6 support. @amykyta3 mentioned that it would be nice to support Python 3.6 in #1. Low-priority, but would be a nice-to-have.

If there are any other things to do, please let me know here.

**Comment by amykyta3** [comment]
I already have admin access to all repos, so that is sufficient. Regarding rtd and pypi, my username is the same.
`drom` only owns a few repos so probably not necessary to add him there.

**Comment by amykyta3** [comment]
Looks good! Thanks

**Comment by MarekPikula** [comment]
Python 3.6 support was added in c00505a08e19f28e33fc0ad63b1a47521cf16fc7.
